# Generated by Django 5.1.1 on 2025-05-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="roombooking",
            name="notification_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="room",
            name="image",
            field=models.ImageField(
                blank=True,
                default="/media/images/default_room.jpg",
                null=True,
                upload_to="images/",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                default="profile_photos/default_user.jpg",
                null=True,
                upload_to="profile_photos/",
            ),
        ),
    ]
