# Generated by Django 5.1.1 on 2025-05-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_roombooking_notification_sent_alter_room_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="bedrooms",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
