# Generated by Django 5.2 on 2025-05-01 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_room_bedrooms"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="supportticket",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="supportticket",
            name="category",
            field=models.CharField(
                choices=[
                    ("booking_issues", "Booking Issues"),
                    ("roommate_concerns", "Roommate Concerns"),
                    ("payment_issues", "Payment Issues"),
                    ("finding_rooms", "Help Finding Rooms"),
                    ("listing_issues", "Listing Issues"),
                    ("booking_management", "Booking Management"),
                    ("tenant_concerns", "Tenant Concerns"),
                    ("payment_processing", "Payment Processing"),
                    ("account_issues", "Account Issues"),
                    ("technical_problems", "Technical Problems"),
                    ("features_request", "Feature Request"),
                    ("general_question", "General Question"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="ticket_type",
            field=models.CharField(
                choices=[
                    ("seeker", "Seeker Support"),
                    ("provider", "Provider Support"),
                    ("general", "General Support"),
                ],
                default="general",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="supportticket",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="supportticket",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name="TicketResponse",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("message", models.TextField()),
                ("staff", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="core.supportticket",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
