# Generated by Django 5.1.1 on 2025-05-01 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_supportticket_options_supportticket_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='contract',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking', to='core.roomcontract'),
        ),
    ]
