# Generated by Django 5.2 on 2025-05-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_supportticket_options_supportticket_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_available",
            field=models.BooleanField(
                default=True,
                help_text="Whether the user is currently available as a roommate",
            ),
        ),
    ]
